# ASP.NET 
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: 'Examples/SQL/Database.EFCore/Database.EFCore.csproj'

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'Examples/SQL/Database.EFCore/Database.EFCore.csproj'
    majorVersion: 1
    minorVersion: 2
    nobuild: true
    versioningScheme: 'off' 

- task: DotNetCoreCLI@2
  displayName: "dotnet push"
  inputs:
    command: 'push'
    majorVersion: 1
    minorVersion: 2
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'DeveloperTools/App_feed'
    
# - task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#    ArtifactName: 'Database.EFCore'
#    publishLocation: 'FilePath'
#    TargetPath: '$(Build.ArtifactStagingDirectory)'
    
    
# - task: NuGetCommand@2
#   displayName: 'nuget push'
#   inputs:
#     command: 'push'
#     feedsToUse: 'select'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/**/drop/*.nupkg'
#     nuGetFeedType: 'internal'
#     vstsFeed: DeveloperTools/App_feed
#     publishVstsFeed: DeveloperTools/App_feed
#     allowPackageConflicts: true
