version: '2.0'
services:
  db:
    image: "${PGIMAGE}"   
    container_name: dev-db 
    ports:
      - "${PGPORT}:5432"
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
      - "./pgdata:/var/lib/postgresql/data"
    environment:
     POSTGRES_USER:     "${PGUSER}"
     POSTGRES_PASSWORD: "${PGPASSWORD}"
     POSTGRES_DB:       "${PGDATABASE}"

  webapp:
    container_name: 'webapp'
    restart: always
    image: webapp
    build:
      context: ./
      dockerfile: webapp.dockerfile
    ports:
      - "5000:80"
    links:
      - "db"
